### ISSUE TITLE
Thanks for your localization efforts (some questions)

### ISSUE THREAD

**Issue by GSYang87** [klausyoum/BLIA#3]
Dear Authors,

Hello,

Thanks for your localization efforts.

I have questions as below:

1. how to connect with bug reports and source files?
I cannot see bug reports related to source file.
e.g., bug_id : 28919 and file : weaver/src/org/aspectj/weaver/bcel/LazyMethodGen.java
Is there any mark in xml file?

How to connect with them please?

2. what the meaning of each columns?
e.g., Resultset_v1.5\Resultset_v1.5\RQ1\Table5\aspectj_alpha_0.3_beta_0.2_gamma_0.4_k_120_cand_rate_0.10_BLIA_File_Excluding_Comments.txt

In the text file,
we can see "28974 weaver/src/org/aspectj/weaver/AjcMemberMaker.java 2"

I think 28974 is bug report id, 2nd column is the recommended (predicted) file, last column is TOP2? :)

Many thanks for your posts.

Yang.

**Comment by klausyoum** [comment]
Dear Mr. Yang,

Thank you for your interests in my research. Well, your question is the first one for me. So it is big pleasure for me and my team. I hope below inline answers help your research.
1. how to connect with bug reports and source files?

I cannot see bug reports related to source file.
e.g., bug_id : 28919 and file : weaver/src/org/aspectj/weaver/bcel/LazyMethodGen.java
Is there any mark in xml file?
_[Klaus] You can find the dataset link at https://github.com/klausyoum/BLIA/wiki . Please refer to the following capture._

![image](https://cloud.githubusercontent.com/assets/8275663/20309588/fd679b80-ab8b-11e6-9286-702445888bbe.png)
1. How to connect with them please? what the meaning of each columns?
   e.g., Resultset_v1.5\Resultset_v1.5\RQ1\Table5\aspectj_alpha_0.3_beta_0.2_gamma_0.4_k_120_cand_rate_0.10_BLIA_File_Excluding_Comments.txt
   In the text file,
   we can see "28974 weaver/src/org/aspectj/weaver/AjcMemberMaker.java 2"

I think 28974 is bug report id, 2nd column is the recommended (predicted) file, last column is TOP2? :)
_[Klaus] Using BLIA application with dataset, you can find the bug localized and evaluated results. Your guess is correct._

Please feel free to ask what you wonder for our research at this workspace.

Thanks,
Klaus.
