### ISSUE TITLE
Continue to study

### ISSUE THREAD

**Issue by FlyStory** [klausyoum/BLIA#6]
was inspired by your paper and it will be very helpful for my research. Since it is your extension of the database, I want to download the git repository to collect more information, such as the last modification time of the method. However, I found that the git address you provided does not have access to your corresponding version. Can you help me? Give me the git address of the corresponding version of zxing1.6 and other projects, or the git source file you downloaded at that time. Thank you very much

**Comment by klausyoum** [comment]
> was inspired by your paper and it will be very helpful for my research. Since it is your extension of the database, I want to download the git repository to collect more information, such as the last modification time of the method. However, I found that the git address you provided does not have access to your corresponding version. Can you help me? Give me the git address of the corresponding version of zxing1.6 and other projects, or the git source file you downloaded at that time. Thank you very much

@FlyStory I am so sorry that I answered your query too lately. I think you already find the moved repositories via Google. Belows repositories are what I just found now. Hope this help you.

* AspectJ : https://github.com/eclipse/org.aspectj
* SWT : https://github.com/eclipse/eclipse.platform.swt
* ZXing : https://github.com/zxing/zxing
